# """Add status column to Todo model

# Revision ID: b10537414af6
# Revises: 
# Create Date: 2024-05-18 16:28:33.548973

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = 'b10537414af6'
# down_revision = None
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('todo', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('todo', schema=None) as batch_op:
#         batch_op.drop_column('status')

#     # ### end Alembic commands ###

"""Add status column to Todo model

Revision ID: b10537414af6
Revises: 
Create Date: 2024-05-18 16:28:33.548973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10537414af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Pending'))

    # Remove the server_default after setting the default value
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###

